language: node_js
sudo: required
dist: trusty
node_js: stable
install:
  - npm install -g purescript purescript-psa pulp bower
script:
  - npm install
  - bower install
  - pulp build -- --stash --censor-lib
  - pulp test
