# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm set prefix ~/.npm
    npm install -g purescript purescript-psa pulp bower
    npm install
    bower install
  displayName: 'install deps'

- script: |
    export PATH=~/.npm/bin:$PATH
    pulp build -- --stash --censor-lib
    pulp test
  displayName: 'build'
